### ISSUE TITLE
tg 这个不知道为什么

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/omega-miya#144]
![image](https://github.com/Ailitonia/omega-miya/assets/69783837/2b122912-9c96-4188-b73a-6c4a60e68956)

**Comment by lancer-wang** [comment]
一开始本地不行，试了改用docker，也不行

FROM python:3.11-bullseye

RUN apt-get update && apt-get install tini

**Comment by lancer-wang** [comment]
```
Traceback (most recent call last):
  File "/cobudy/omega-miya/bot.py", line 45, in <module>
    driver.register_adapter(TelegramAdapter)
  File "/root/.cache/pypoetry/virtualenvs/omega-miya-INK4gXnZ-py3.11/lib/python3.11/site-packages/nonebot/internal/driver/abstract.py", line 91, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/omega-miya-INK4gXnZ-py3.11/lib/python3.11/site-packages/nonebot/adapters/telegram/adapter.py", line 32, in __init__
    self.adapter_config = AdapterConfig(**self.config.model_dump())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/omega-miya-INK4gXnZ-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AdapterConfig
telegram_bots.0
  Input should be a valid dictionary or instance of BotConfig [type=model_type, input_value='7327504091:AAHYp5afe67-w2gdalspLTDtHmCKzX8qchU', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type

```

**Comment by lancer-wang** [comment]
解决了，是配置填写问题

不过这个不知道为什么， No module named '_lzma'
![image](https://github.com/Ailitonia/omega-miya/assets/69783837/2df0690a-45d2-47dc-b0a5-27ada3bd48b7)

**Comment by Ailitonia** [comment]
好像是上游问题 https://github.com/miurahr/py7zr/issues/382
不过我都是 windows 环境，没有在 ubuntu 上测试过😂
