### ISSUE TITLE
考虑一下写个详细点的教程…?

### ISSUE THREAD

**Issue by yusana213214** [Ailitonia/omega-miya#42]
教程好简略啊，数据库配置直接给我整蒙了，看不懂

**Comment by Ailitonia** [comment]
会考虑改进下README
不过详细的教程嘛emmmmmm
咕咕咕

**Comment by yusana213214** [comment]
> 会考虑改进下README
> 不过详细的教程嘛emmmmmm
> 咕咕咕

大佬数据库那一栏到底该怎么改，整不会

**Comment by Ailitonia** [comment]
> > 会考虑改进下README
> > 不过详细的教程嘛emmmmmm
> > 咕咕咕
> 
> 大佬数据库那一栏到底该怎么改，整不会

看这个吧
虽然写着也比较简单不过配置项都有说明

**Comment by lancer-wang** [comment]
> > 会考虑改进下README
> > 不过详细的教程嘛emmmmmm
> > 咕咕咕
> 
> 大佬数据库那一栏到底该怎么改，整不会

你是不是没用过数据库
百度一下phpstudy,然后用phpstudy一键创建一个数据库
![image](https://user-images.githubusercontent.com/69783837/124530108-765bd300-de3e-11eb-891b-f8d740d5fe7a.png)

**Comment by AinoAty** [comment]
跟着教程走配置成功了，，但是启动不了，[ERROR] nonebot | Failed to import "omega_sign_in"

**Comment by lancer-wang** [comment]
> 跟着教程走配置成功了，，但是启动不了，[ERROR] nonebot | Failed to import "omega_sign_in"

感觉应该是没导入某个库,建议报错贴全一点,

**Comment by AinoAty** [comment]
> > 跟着教程走配置成功了，，但是启动不了，[ERROR] nonebot | Failed to import "omega_sign_in"
> 
> 感觉应该是没导入某个库,建议报错贴全一点,

05-20 09:00:51 [SUCCESS] nonebot | NoneBot is initializing...
05-20 09:00:51 [INFO] nonebot | Current Env: prod
05-20 09:00:52 [SUCCESS] nonebot | Succeeded to import "dice_utils"
05-20 09:00:53 [SUCCESS] nonebot | Succeeded to import "tencent_cloud_api"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "pixiv_utils"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "nhentai_utils"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_processor"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_plugin_utils"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_multibot_support"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_adapter"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "nonebot_guild_patch"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "nhentai"
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
05-20 09:00:54 [INFO] omega_manager | HTTP 代理: 已禁用!
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_manager"
05-20 09:00:54 [ERROR] nonebot | Failed to import "omega_sign_in"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\omega-miya\bot.py", line 56, in <module>
    nonebot.load_plugins("omega_miya/plugins")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "omega_miya/plugins\omega_sign_in\__init__.py", line 26, in <module>
    from .utils import scheduler, get_hitokoto, generate_sign_in_card
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "omega_miya/plugins\omega_sign_in\utils.py", line 131, in <module>
    def __get_level(favorability: float) -> tuple[int, int, int]:
TypeError: 'type' object is not subscriptable
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_recaller"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "omega_help"
05-20 09:00:54 [SUCCESS] nonebot | Succeeded to import "miya_button"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_statistic"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_auth_manager"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "maybe"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_rate_limiting"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_skill"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_invite_manager"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "omega_plugins_manager"
05-20 09:00:55 [SUCCESS] nonebot | Succeeded to import "su_self_sent"
05-20 09:00:55 [SUCCESS] nonebot | Running NoneBot...
05-20 09:00:55 [INFO] uvicorn | Started server process [4844]
05-20 09:00:55 [INFO] uvicorn | Waiting for application startup.
05-20 09:00:55 [INFO] omega_miya | 正在初始化数据库......
05-20 09:00:55 [SUCCESS] omega_miya | 数据库初始化已完成.
05-20 09:00:55 [INFO] omega_plugin_utils | Fragment process | Startup Init Plugins processing: 1/1
05-20 09:00:55 [SUCCESS] omega_plugin_utils | Fragment process | Startup Init Plugins processing complete successful, total tasks: 23
05-20 09:00:55 [SUCCESS] omega_processor | 插件信息初始化已完成.
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\triggers\cron\__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\triggers\cron\__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
05-20 09:00:56 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-20 09:00:56 [INFO] uvicorn | Application startup complete.
05-20 09:00:56 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:3322 (Press CTRL+C to quit)
