### ISSUE TITLE
关于功能的疑问&一些建议

### ISSUE THREAD

**Issue by sola614** [Ailitonia/omega-miya#56]
疑问：   
1.来点萌图 / 来点涩图这个功能是要自己导入图片吗？使用`/来点萌图`都会提示`找不到萌图QAQ`（机器人已部署在外网）   
建议：   
1.能否增加油管订阅   
2.能否增加推特订阅   
3.能否增加嘴臭功能   
4.抽卡功能增加PCR和原神

**Comment by Ailitonia** [comment]
1.1 图库如果自己懒得收集可以看 [README-导入图片数据库](https://github.com/Ailitonia/omega-miya/blob/master/README.md#%E5%85%B3%E4%BA%8E%E5%9B%BE%E7%89%87%E6%95%B0%E6%8D%AE)


2.1 目前主要在对 bot 的一些基础功能做调整和优化, 油管相关算是计划中的功能吧, 另外油管的 api 还需要我研究下
2.2 同上, 之前计划过, 不过推的 api 更麻烦一些, 另外考虑到国内网络安全问题, 实装这个功能可能emmmm, 另: 以上两个功能将在订阅表调整后重新规划 https://github.com/Ailitonia/omega-miya/issues/32#issuecomment-898231562
2.3 不会加, 另: 聊天交互是一个更远的计划, 将是好感度系统的重要部分
2.4 不玩pcr和原神, 需要抽卡插件的话 nb2 商店里面有更好的
2.5 查股票请使用专业应用

**Comment by sola614** [comment]
好，谢谢dalao

**Comment by wangjiahui1126** [comment]
1希望有网页UI的插件开关
2dev版本和master版本是不是不共存？ 同一台电脑上，打开dev版本的bot一堆警告并且无法正常使用。 回去用master版本的bot也多了几个报错，虽然还能正常用。 （2边的依赖都已安装，系统是windows sever2019）
3希望有讨论群呀，大佬

这是其中一小段报错
10-03 02:04:33 [ERROR] nonebot | Failed to import "Omega_plugin_utils"
Traceback (most recent call last):
  File "C:\bot\omega-miya\bot.py", line 49, in <module>
    nonebot.load_plugins("omega_miya/utils")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 997, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 945, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in impor

**Comment by Ailitonia** [comment]
> 1希望有网页UI的插件开关
> 2dev版本和master版本是不是不共存？ 同一台电脑上，打开dev版本的bot一堆警告并且无法正常使用。 回去用master版本的bot也多了几个报错，虽然还能正常用。 （2边的依赖都已安装，系统是windows sever2019）
> 3希望有讨论群呀，大佬

1. 不会前端开发QAQ
2. 目前不共存，项目结构已有较大调整
3. 暂时没有精力维护

**Comment by Ailitonia** [comment]
好像可以拿现成的前端管理模板来魔改🤔

**Comment by Peiyu1230** [comment]
可以帮忙写一下go-cqhttp configer的文件配置吗 我这里改了半天go-cqhttp可以正常启动 但是nonebot 协议端无法连接

**Comment by Lycofuture** [comment]
可以配置redis数据库吗，系统不支持mysql数据库
