### ISSUE TITLE
群青表情包模板收到gif图时制作失败

### ISSUE THREAD

**Issue by ShianoQwQ** [Ailitonia/omega-miya#96]
提示“表情包制作失败了QAQ, 发生了意外的错误, 请稍后再试”，而不是像别的模板转成了静态图。

使用的[7f8b68e](https://github.com/Ailitonia/omega-miya/commit/7f8b68edb0ee6a023bb2eefaf65bd1710f01dbc0)

**Comment by ShianoQwQ** [comment]
补充一个日志
```
06-18 11:43:02 [ERROR] omega_miya | Decorator RunAsyncCatchingException | omega_miya.plugins.sticker_maker.model.make raise Exception ValueError > There are something wrong(s) in function running
Traceback (most recent call last):
  File "/home/shiano/omega-miya/omega_miya/plugins/sticker_maker/__init__.py", line 141, in handle_sticker
    sticker_result = await run_async_catching_exception(sticker_render(text=text, source_image=source_image).make)()
> File "/home/shiano/omega-miya/omega_miya/utils/process_utils/__init__.py", line 128, in _wrapper
    result = await func(*args, **kwargs)
  File "/home/shiano/omega-miya/omega_miya/plugins/sticker_maker/model.py", line 127, in make
    image_content = await run_sync(self._handler)()
  File "/home/shiano/omega-miya/omega_miya/utils/process_utils/__init__.py", line 84, in _wrapper
    return await loop.run_in_executor(None, p_func)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/shiano/omega-miya/omega_miya/plugins/sticker_maker/render.py", line 584, in _handler
    made_image = ImageEnhance.Color(image).enhance(0)
  File "/home/shiano/bot/lib/python3.10/site-packages/PIL/ImageEnhance.py", line 36, in enhance
    return Image.blend(self.degenerate, self.image, factor)
  File "/home/shiano/bot/lib/python3.10/site-packages/PIL/Image.py", line 3167, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: image has wrong mode
06-18 11:43:02 [ERROR] omega_miya | StickerMaker | 制作表情包失败, image has wrong mode```

**Comment by Ailitonia** [comment]
周末有空来修😂

**Comment by Ailitonia** [comment]
Fixed in ac134f77f6d54050c5c739d88471d8175ca7237a
